repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
      language_version: python3.12
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.4.7
  hooks:
    - id: ruff
      args: ["--fix"]
